
ServerEvents.tags('block', event => {
	event.add('lostcities:lights', 'minecraft:lantern')
	event.add('lostcities:lights', 'minecraft:torch')
	event.add('lostcities:lights', 'minecraft:soul_torch')
	event.add('lostcities:lights', 'minecraft:redstone_torch')
	event.add('lostcities:lights', 'minecraft:sea_lantern')
	event.add('lostcities:lights', 'minecraft:glowstone')
	event.add('lostcities:lights', 'minecraft:campfire')
	event.add('lostcities:lights', 'simplylight:rodlamp')
	event.add('lostcities:lights', 'simplylight:wall_lamp')
	event.add('lostcities:lights', 'simplylight:lightbulb')
	event.add('lostcities:lights', 'simplylight:illuminant_block_on')
	event.add('lostcities:lights', 'simplylight:illuminant_yellow_block_on')
	event.add('lostcities:lights', 'simplylight:illuminant_panel')
	event.add('lostcities:lights', 'simplylight:edge_light_top')
	event.add('lostcities:lights', 'simplylight:edge_light')
	event.add('lostcities:lights', 'simplylight:illuminant_light_gray_block_on')
	event.add('lostcities:lights', 'simplylight:lamp_post')
	event.add('lostcities:lights', 'quark:paper_lantern_sakura')
	event.add('lostcities:lights', 'quark:paper_lantern')
	event.add('lostcities:lights', 'quark:blaze_lantern')
	event.add('lostcities:lights', 'immersiveengineering:lantern')
	event.add('lostcities:lights', 'buildersdelight:lantern_4')
	event.add('lostcities:lights', 'another_furniture:lamps')
})
